---
# tasks file for origin_host
- name: make sure origin host base packages are installed
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"

- name: replace docker config file with the one we want
  copy:
    src: docker_config
    dest: /etc/sysconfig/docker

- name: restart docker service, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker.service