---
# tasks file for origin_host
- name: make sure origin host base packages are installed
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"

- name: replace docker config file with the one we want
  copy:
    src: docker_config
    dest: /etc/sysconfig/docker

- name: restart docker service, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker.service

- name: yum
  yum: name={{item}} state=latest
  with_items: "{{ python_yum }}"

- name: unarchive
  unarchive:
    src: "{{ python_url }}"
    dest: "{{ python_tmp }}"
    remote_src: True
  register: reg

- name: make
  shell: cd "{{ python_dir }}" && ./configure --prefix=/usr/local/python && make && make install

- name: symlink python and pip
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: '/usr/local/python/bin/python3', dest: '/usr/local/bin/python' }
    - { src: '/usr/local/python/bin/pip3'   , dest: '/usr/local/bin/pip'    }

- name: instal python packages
  pip:
    name: pyyaml