- hosts: ansible

  tasks:
    - name: create test vm
      proxmox_kvm:
        api_user: root@pam
        api_password: "!kF78afer"
        api_host: 32.32.0.3
        name: testitude
        node: node2
        state: present
        storage: Disks
        format: qcow2
        net: '{"net0":"virtio=AA:BB:CC:DD:EE:11,bridge=vmbr0,rate=200"}'
        timeout: 500
