- hosts: ansible
  become: true

  tasks:
    - name: create test vm
      proxmox_kvm:
        api_user: root@pam
        api_password: "!kF78afer"
        api_host: 32.32.0.3
        name: spynal
        node: node2
        state: started