---
proxmox:
  hosts:
    node0:
      ansible_host: 32.32.0.3
    node1:
      ansible_host: 32.32.0.4
    node2:
      ansible_host: 32.32.0.5
    node3:
      ansible_host: 32.32.0.6
  vars:
    ansible_user: root
ansible:
  hosts:
    ansible-controller:
      ansible_become: true
      ansible_connection: local
linux:
  children:
    proxmox:
    ansible:
  vars:
    host_os_family: Debian