---
  api_user: root@pam
  api_password: "!kF78afer"
  api_host: 32.32.0.6
  vm_info:
    -
      name: n1-openshift
      vm_location: node0
      memory: 16384
      cores: 4
      clone: centos7-template
      template_location: node3
      meta: { "groups": ["masters","OSEv3", "nodes", "linux"] }
    - 
      name: n1-nodes-1
      vm_location: node1
      memory: 16384
      cores: 4
      clone: centos7-template
      template_location: node3
      meta: { "groups": ["OSEv3", "etcd", "nodes", "lb", "workers", "linux"] }
    -
      name: n1-nodes-2
      vm_location: node2
      memory: 16384
      cores: 4
      clone: centos7-template
      template_location: node3
      meta: { "groups": ["OSEv3", "etcd", "nodes", "workers", "linux"] }
    -
      name: n1-nodes-3
      vm_location: node3
      memory: 16384
      cores: 4
      clone: centos7-template
      template_location: node3
      meta: { "groups": ["OSEv3", "etcd", "nodes", "workers", "linux"] }
    