---
- name: create/update vms
  proxmox_kvm:
  # General
    state: "{{state}}"
    api_host: "{{api_host}}"
    api_user: "{{api_user}}"
    api_password: "{{api_password}}"
    timeout: 500
  # VM specific - mandatory
    name: "{{item.name}}"
    node: "{{ (item.clone != None) | ternary(item.template_location, item.vm_location) }}"
  # VM specific - optional
    clone: "{{item.clone | default(omit)}}"
    cores: "{{item.cores | default(1)}}"
    cpu: "{{item.cpu | default('kvm64')}}"
    memory: "{{item.memory | default(512)}}"
    net: "{{item.net | default(omit)}}"
    ostype: "{{item.ostype | default('l26')}}"
    pool: "{{item.pool | default(omit)}}"
    scsi: "{{item.scsi | default(omit)}}"
    storage: "{{item.storage | default(omit)}}"
    target: "{{ ((item.clone != None) | ternary(item.vm_location, omit)) }}"
    template: "{{item.template | default('no')}}"
    description: "{{ item.meta | default(omit)}}"
  with_items: "{{vm_info}}"
  when: state == 'present'

- name: update vms
  proxmox_kvm:
  # General
    api_host: "{{api_host}}"
    api_user: "{{api_user}}"
    api_password: "{{api_password}}"
  # VM specific - mandatory
    name: "{{item.name}}"
    node: "{{item.vm_location}}"
    description: "{{ item.meta | default(omit)}}"
    update: yes
  with_items: "{{vm_info}}"
  when: state == 'present'

- name: delete/start/restart vms
  proxmox_kvm:
  # General
    state: "{{state}}"
    api_host: "{{api_host}}"
    api_user: "{{api_user}}"
    api_password: "{{api_password}}"
  # VM specific
    name: "{{item.name}}"
    node: "{{item.vm_location}}"
  with_items: "{{vm_info}}"
  when: state != 'present'