---
api_user: root@pam
api_password: "!kF78afer"
api_host: 32.32.0.3
vm_info:
  -
    name: kubespray-1
    vm_location: node0
    memory: 16384
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-master","etcd", "kube-node", "linux", "kubespray-12node-k8s"] }
  - 
    name: kubespray-2
    vm_location: node1
    memory: 16384
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-master","etcd", "kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-3
    vm_location: node2
    memory: 16384
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-master","etcd", "kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-4
    vm_location: node3
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-5
    vm_location: node0
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-6
    vm_location: node1
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-7
    vm_location: node2
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-8
    vm_location: node3
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-9
    vm_location: node0
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-10
    vm_location: node1
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-11
    vm_location: node2
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
  -
    name: kubespray-12
    vm_location: node3
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["kube-node", "linux", "kubespray-12node-k8s"] }
