---
api_user: root@pam
api_password: "!kF78afer"
api_host: 32.32.0.3
vm_info:
  -
    name: k8s-master-1
    vm_location: node0
    memory: 16384
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["masters","openshift-nodes"] }
  - 
    name: k8s-master-2
    vm_location: node1
    memory: 16384
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["masters","openshift-nodes"] }
  -
    name: k8s-master-3
    vm_location: node2
    memory: 16384
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["masters","openshift-nodes"] }
  -
    name: k8s-infra-1
    vm_location: node3
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["infras","openshift-nodes"] }
  -
    name: k8s-infra-2
    vm_location: node0
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["infras","openshift-nodes"] }
  -
    name: k8s-loadbalancer-1
    vm_location: node1
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["load-balancers","openshift-nodes"] }
  -
    name: k8s-app-1
    vm_location: node2
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["app-hosts","openshift-nodes"] }
  -
    name: k8s-app-2
    vm_location: node3
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["app-hosts","openshift-nodes"] }
  -
    name: k8s-app-3
    vm_location: node0
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["app-hosts","openshift-nodes"] }
  -
    name: k8s-app-4
    vm_location: node1
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["app-hosts","openshift-nodes"] }
  -
    name: k8s-app-5
    vm_location: node2
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: { "groups": ["app-hosts","openshift-nodes"] }
  -
    name: k8s-app-6
    vm_location: node3
    memory: 8192
    cores: 4
    clone: centos7-template
    template_location: node3
    meta: "{ 'groups': ['app-hosts','openshift-nodes'] }"