---
- name: create vm fleet for production environment
  hosts: ansible
  become: true
  vars_files:
  - ../configs/admonexample.yml

- name: create vm fleet
  include_role:
    name: proxmox_kvm_fleet
  
- name: create vm fleet
  include_role:
    name: proxmox_kvm_fleet
  vars:
    state: started

- name: initial prep on vms
  hosts: OSEv3
  vars:
    ansible_password: '!kF78afer'
  roles:  
  - core_linux

- name: origin prep on vms
  import_playbook: ../../openshift-ansible/playbooks/prerequisites.yml

- name: install origin on vms
  import_playbook: ../../openshift-ansible/playbooks/deploy_cluster.yml